query MeWithMerchantUsers {
    me {
        ...user
        merchantUsers {
            nodes {
                id
                merchant {
                    name
                    id
                }
                role
                status
            }
        }
    }
}