fragment user on User {
    id
    firstName
    lastName
    language
    email
    phone
    confirmedAt
    state
    status
    dob
    citizenIdNumber
    externalKycId
    gender
    language
    spcWallet {
        ...wallet
    }
}