query Me {
    me {
        ...user
        merchantUsers {
            nodes {
                ...merchantUser
            }
        }
        merchants {
            nodes {
                ...merchant
            }
        }
    }
}