query Me($merchantFilter: MerchantFilter, $merchantUserFilter: MerchantUserFilter) {
    me {
        ...user
        merchantUsers(filter: $merchantUserFilter) {
            nodes {
                ...merchantUser
            }
        }
        merchants(filter: $merchantFilter) {
            nodes {
                ...merchant
            }
        }
    }
}